"""Sphinx configuration for the pytest-plone documentation.

The API reference is generated by ``sphinx-autodoc2`` rather than
``sphinx.ext.autodoc``. Two properties of this package make that necessary:

1. ``@pytest.fixture`` returns a ``FixtureFunctionDefinition`` object, not a
   function. ``sphinx.ext.autodoc`` introspects live objects, so it cannot
   document our fixtures. ``sphinx-autodoc2`` analyses the source statically,
   so the decorator is irrelevant to it.
2. Our docstrings are written in Markdown. ``sphinx.ext.autodoc`` hands
   docstrings to the reStructuredText parser, which mangles them.
   ``autodoc2_docstring_parser_regexes`` below parses them as MyST instead.

Because the analysis is static, building these docs does not import the
package. No Plone installation is required.
"""

from datetime import datetime
from packaging.version import Version
from pytest_plone import __version__


project = "pytest-plone"
author = "Plone Community"
trademark_name = "plone"
now = datetime.now()
year = str(now.year)
copyright = year  # noQA: A001
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
release = __version__
# The short X.Y version.
version = "v" + (Version(str(release)).base_version)

templates_path = ["_templates"]

extensions = [
    "notfound.extension",
    "autodoc2",
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_sitemap",
    "sphinxext.opengraph",
]

# -- autodoc2 ---------------------------------------------------------------

# The path must be relative to this file. An absolute path raises
# ``autodoc2.config_error``.
autodoc2_packages = [
    {
        "path": "../src/pytest_plone",
        "auto_mode": False,
    },
]

# We place ``{autodoc2-object}`` directives by hand inside curated reference
# pages, so autodoc2 must not generate an API tree of its own.
autodoc2_render_plugin = "myst"

# Parse every docstring as MyST, not reStructuredText.
autodoc2_docstring_parser_regexes = [
    (r".*", "myst"),
]

# -- MyST -------------------------------------------------------------------

myst_enable_extensions = [
    "attrs_inline",
    "colon_fence",
    "deflist",
    # Required. Without it, reST field syntax (``:param x:``) in a docstring
    # renders as literal text instead of a parameter list.
    "fieldlist",
    "linkify",
    "substitution",
]

myst_heading_anchors = 3

# -- Intersphinx-free external links ----------------------------------------

linkcheck_ignore = [
    r"http://0.0.0.0",
    r"http://127.0.0.1",
    # Anchors on GitHub are generated client-side.
    r"https://github\.com/.*#.*",
]

# -- HTML output ------------------------------------------------------------

html_theme = "plone_sphinx_theme"

html_logo = "_static/logo.svg"
html_favicon = "_static/favicon.ico"

html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/plone/pytest-plone",
            "icon": "fa-brands fa-square-github",
            "type": "fontawesome",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/pytest-plone/",
            "icon": "fa-brands fa-python",
            "type": "fontawesome",
        },
    ],
    "logo": {"text": "pytest-plone"},
    "navigation_with_keys": True,
    "path_to_docs": "docs",
    "repository_branch": "main",
    "repository_url": "https://github.com/plone/pytest-plone",
    "search_bar_text": "Search",
    "show_toc_level": 2,
    "use_edit_page_button": True,
    "use_issues_button": True,
    "use_repository_button": True,
}

html_sidebars = {
    "**": [
        "navbar-logo",
        "search-button-field",
        "sbt-sidebar-nav",
    ]
}

html_title = f"{project} v{release}"

html_extra_path = [
    "robots.txt",
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
    "_static",
]

html_baseurl = "https://plone.github.io/pytest-plone"
sitemap_url_scheme = "{link}"
sitemap_filename = "sitemap-custom.xml"
