"""Sphinx configuration for the pytest-plone documentation.

The API reference is generated by ``sphinx-autodoc2`` rather than
``sphinx.ext.autodoc``. Two properties of this package make that necessary:

1. ``@pytest.fixture`` returns a ``FixtureFunctionDefinition`` object, not a
   function. ``sphinx.ext.autodoc`` introspects live objects, so it cannot
   document our fixtures. ``sphinx-autodoc2`` analyses the source statically,
   so the decorator is irrelevant to it.
2. Our docstrings are written in Markdown. ``sphinx.ext.autodoc`` hands
   docstrings to the reStructuredText parser, which mangles them.
   ``autodoc2_docstring_parser_regexes`` below parses them as MyST instead.

Because the analysis is static, building these docs does not import the
package. No Plone installation is required.
"""

project = "pytest-plone"
copyright = "2026, Plone Foundation"
author = "Plone Community"

extensions = [
    "autodoc2",
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
]

# -- autodoc2 ---------------------------------------------------------------

# The path must be relative to this file. An absolute path raises
# ``autodoc2.config_error``.
autodoc2_packages = [
    {
        "path": "../src/pytest_plone",
        "auto_mode": False,
    },
]

# We place ``{autodoc2-object}`` directives by hand inside curated reference
# pages, so autodoc2 must not generate an API tree of its own.
autodoc2_render_plugin = "myst"

# Parse every docstring as MyST, not reStructuredText.
autodoc2_docstring_parser_regexes = [
    (r".*", "myst"),
]

# -- MyST -------------------------------------------------------------------

myst_enable_extensions = [
    "attrs_inline",
    "colon_fence",
    "deflist",
    # Required. Without it, reST field syntax (``:param x:``) in a docstring
    # renders as literal text instead of a parameter list.
    "fieldlist",
    "linkify",
    "substitution",
]

myst_heading_anchors = 3

# -- Intersphinx-free external links ----------------------------------------

linkcheck_ignore = [
    # Anchors on GitHub are generated client-side.
    r"https://github\.com/.*#.*",
]

# -- HTML output ------------------------------------------------------------

html_theme = "plone_sphinx_theme"

html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/plone/pytest-plone",
            "icon": "fa-brands fa-square-github",
            "type": "fontawesome",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/pytest-plone/",
            "icon": "fa-brands fa-python",
            "type": "fontawesome",
        },
    ],
    "logo": {"text": "pytest-plone"},
    "navigation_with_keys": True,
    "path_to_docs": "docs",
    "repository_branch": "main",
    "repository_url": "https://github.com/plone/pytest-plone",
    "search_bar_text": "Search",
    "show_toc_level": 2,
    "use_edit_page_button": True,
    "use_issues_button": True,
    "use_repository_button": True,
}

html_sidebars = {
    "**": [
        "navbar-logo",
        "search-button-field",
        "sbt-sidebar-nav",
    ]
}
